# Change these first
owner: infiSCALE # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: infiSCALE™ Home
    url: https://www.infiscale.io
  - name: infiSCALE™ Magento Shop
    url: https://shop.infiscale.io
  - name: infiSCALE™ CMS
    url: https://www.infiscale.io/wp-admin/
  - name: infiSCALE™ GraphQL
    url: https://www.infiscale.io/graphql/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: infiSCALE™
  introTitle: "At **infiSCALE™**, we take pride in our dynamism and innovative approach toward software development services using some of the most dynamic products available within the Adobe suite of products such as Experience Manager, Commerce or Analytics- to name a few! Our key objective is centered around helping businesses from diverse fields realize the full potential of their software investments for transformative digital experiences."
  introMessage: "We aim at building enduring partnerships with all our clients where adding exceptional value consistently is our topmost priority. Some examples would include end-to-end website creation management; insights-driven revenue growth optimization and pioneering experimentation strategies that enable fresh thinking and drive competitiveness amidst evolving challenges across industries. "
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
